[package]
name = "om-ict2"
version = "0.1.0"
authors = ["Tokarev Artyom <tokarev28.art@gmail.com>"]
edition = "2018"

[dependencies]
om-gs = { path = "../om-gs", version = "*" }
om-sd = { path = "../om-sd", version = "*" }
om-hj = { path = "../om-hj", version = "*" }
